<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit533a5a96b69b895b12e0266639f57301
{
    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Smalot\\PdfParser\\' => 
            array (
                0 => __DIR__ . '/..' . '/smalot/pdfparser/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit533a5a96b69b895b12e0266639f57301::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
